# Generated by Django 2.0.2 on 2018-03-01 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('dynasty', models.CharField(default='S', max_length=10)),
                ('author_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'poems_author',
            },
        ),
        migrations.CreateModel(
            name='PoemAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('intro_l', models.TextField()),
                ('intro_s', models.TextField()),
                ('dynasty', models.CharField(default='S', max_length=10, null=True)),
            ],
            options={
                'db_table': 'poems_author',
            },
        ),
        migrations.CreateModel(
            name='Poetry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('dynasty', models.CharField(max_length=10)),
                ('author_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'poetry',
            },
        ),
        migrations.CreateModel(
            name='PoetryAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('intro', models.TextField(blank=True, null=True)),
                ('dynasty', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'poetry_author',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poem.Question'),
        ),
    ]
