# Generated by Django 2.0.2 on 2018-03-01 07:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='author_id',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='poem.PoemAuthor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poetry',
            name='author_id',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='poem.PoetryAuthor'),
            preserve_default=False,
        ),
    ]
