# Generated by Django 2.0.2 on 2018-04-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poetry',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
