# Generated by Django 2.0.2 on 2018-03-01 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0002_auto_20180301_1502'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='poem',
            table='poems',
        ),
    ]
