# Generated by Django 2.0.2 on 2018-04-04 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0002_auto_20180403_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profileuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poem.ProfileUser')),
                ('login_type', models.CharField(max_length=20)),
                ('weichat_id', models.CharField(max_length=100, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=100)),
                ('create_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('favorate_peotry', models.ManyToManyField(to='poem.Poetry')),
                ('favorate_poem', models.ManyToManyField(to='poem.Poem')),
            ],
            bases=('poem.profileuser',),
        ),
    ]
