# Generated by Django 2.0.2 on 2018-04-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0002_auto_20180409_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weichat_session_key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
