# Generated by Django 2.0.2 on 2018-04-04 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0003_profile_profileuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorate_peotry',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favorate_poem',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profileuser_ptr',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='ProfileUser',
        ),
    ]
