# Generated by Django 2.0.4 on 2018-04-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0003_user_weichat_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avataUrl',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(max_length=2, null=True),
        ),
    ]
