# Generated by Django 2.0.4 on 2018-04-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0004_auto_20180410_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='type',
            field=models.CharField(default='poem', max_length=10),
        ),
        migrations.AddField(
            model_name='poetry',
            name='type',
            field=models.CharField(default='poetry', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(null=True),
        ),
    ]
