# Generated by Django 2.0.4 on 2018-04-11 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0005_auto_20180411_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorate_poem',
        ),
    ]
