# Generated by Django 2.0.4 on 2018-04-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0006_remove_user_favorate_poem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='favorate_peotry',
            new_name='favourate_peotry',
        ),
        migrations.AddField(
            model_name='user',
            name='favourate_author',
            field=models.ManyToManyField(to='poem.Author'),
        ),
    ]
