# Generated by Django 2.0.4 on 2018-04-17 01:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0007_auto_20180411_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favourate_author',
        ),
        migrations.AddField(
            model_name='author',
            name='favour_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
