# Generated by Django 2.0.4 on 2018-04-18 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0008_auto_20180417_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favourate_peotry',
        ),
        migrations.AddField(
            model_name='poetry',
            name='favour_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poem.Author'),
        ),
    ]
